[tool.poetry]
name = "polars_splitters"
version = "0.1.0"
description = ""
authors = ["Jonas M. Miguel <Jonas M. Miguel>"]
readme = "README.md"
packages = [{ include = "polars_splitters" }]

[tool.poetry.dependencies]
python = ">3.9, <4.0"
polars = "^0.19.3"
loguru = "^0.7.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
